config/routes.rb
Rails.application.routes.draw do
  root :to => 'news#index'
  resources :comments
  resources :newcomments
  resources :users do
    collection do
      get :logout
      get :about
    end
  end
  resources :news
  resources :submit
  resources :login
  namespace :v0 do
    resources :comment
    resources :new
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :new
  validates :content, length: { in: 3...1000 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @new = New.find(params[:id])
    @comments = @new.comments.order(created_at: :desc)
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = signed_user.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_back fallback_location: root_path, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_back fallback_location: root_path, notice: @comment.errors.full_messages.join(',') }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :new_id)
    end
end

app/controllers/v0/comment_controller.rb
class V0::CommentController < ActionController::Base

  # get http://localhost:3000/v0/comment.json
  def index
    @comments = Comment.all
  end

  # get http://localhost:3000/v0/comment/1.json
  def show
    @comment = Comment.find(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :new_id %>
    <%= form.text_area :content, id: :comment_content %>
  </div>

  <div class="actions">
    <%= form.submit "add comment" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<% content_for :title, @new.title %>

<p id="notice"><%= notice %></p>

<div class="media comment-index">
  <div class="media-body">
    <h4 class="media-heading"><%= "#{@new.title} (#{@new.source}) " %></h4>
  </div>
  <div class="ml-1">
    <% comment_size = @new.comments.size %>
    <%= "by #{@new.user.username} #{time_ago_in_words(@new.created_at)} ago | #{comment_size > 0 ? comment_size.to_s + ' comments' : 'no comments'}" %>
  </div>
</div>
<%= render 'comments/form', comment: @new.comments.new %>

<div class="media">
  <% @comments.each do |comment| %>
    <div class="">
      <%= "by #{comment.user.username} #{time_ago_in_words(comment.created_at)} ago" %>
    </div>
    <div class="media-body ml-1">
      <h4 class="media-heading"><%= comment.content %></h4>
    </div>
  <% end %>
</div>

<br>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/newcomments.html.erb
<% content_for :title, 'New Comments' %>

<div class="media">
  <% @comments.each do |comment| %>
    <div class="">
      <%= "#{comment.user.username} #{time_ago_in_words(comment.created_at)} ago | on: #{comment.new.title}" %>
    </div>
    <div class="media-body ml-1">
      <h4 class="media-heading"><%= comment.content %></h4>
    </div>
  <% end %>
</div>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>