config/routes.rb
Rails.application.routes.draw do
  root :to => 'news#index'
  resources :comments
  resources :newcomments
  resources :users do
    collection do
      get :logout
      get :about
    end
  end
  resources :news
  resources :submit
  resources :login
  namespace :v0 do
    resources :comment
    resources :new
  end
end

app/models/new.rb
class New < ApplicationRecord
  has_many :comments
  validates :source, allow_blank: true, format: { with: /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)/, message: 'is invalid url' }
  validates :title, length: { in: 10...200 }
  belongs_to :user
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  skip_before_action :authencation, only: [:index]
  PAGE_NUMBER = 8

  # GET /news
  # GET /news.json
  def index
    @page = (params[:p] || 0).to_i
    @start = @page * PAGE_NUMBER
    @news = New.all.offset(@start).limit(PAGE_NUMBER).order(created_at: :desc)
    @has_more = (New.all.size - PAGE_NUMBER * (@page + 1)) > 0
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = signed_user.new.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'New was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'New was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_url, notice: 'New was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = New.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:new).permit(:title, :source)
    end
end

app/controllers/v0/new_controller.rb
class V0::NewController < ActionController::Base

  # get http://localhost:3000/v0/new.json
  def index
    @news = New.all
  end

  # get http://localhost:3000/v0/new/1.json
  def show
    @new = New.find(params[:id])
  end

  # post http://localhost:3000/v0/new
  def create
    user = User.find_by_username(params[:username])
    @new = user.new.new(title: params[:text], source: params['new source'])
    p params['new source']
    @new.save!
    render json: {message: 'ok'}, status: 200
  rescue => e
    render json: {message: 'bad'}, status: 400
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_with(model: news, local: true, url: news_index_path) do |form| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title, id: :news_title %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.url_field :source, id: :news_source, placeholder: 'https://' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_path %>

app/views/news/index.html.erb
<%= content_for :title, "Home Page #{@page}" %>
<p id="notice"><%= notice %></p>

<div class="media news-index">
  <% @news.each_with_index do |new, index| %>
    <div class="media-body">
      <h4 class="media-heading"><%= "#{@start + index + 1}. #{new.title} #{new.source.present? ? "(#{link_to new.source, new.source})" : '' }".html_safe %></h4>
    </div>
    <div class="ml-1">
      <% comment_size = new.comments.size %>
      <%= "by #{new.user.username} #{time_ago_in_words(new.created_at)} ago | #{link_to "#{comment_size > 0 ? new.comments.size.to_s + ' comments' : 'no comments'}", comments_path(id: new.id)}".html_safe %>
    </div>
  <% end %>
</div>
<br>
<% if @has_more %>
  <%= link_to 'More', news_index_path(p: @page + 1) %>
<% end %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Source:</strong>
  <%= @news.source %>
</p>

<%= link_to 'Back', news_index_path %>