config/routes.rb
Rails.application.routes.draw do
  root :to => 'news#index'
  resources :comments
  resources :newcomments
  resources :users do
    collection do
      get :logout
      get :about
    end
  end
  resources :news
  resources :submit
  resources :login
  namespace :v0 do
    resources :comment
    resources :new
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  skip_before_action :authencation, only: [:index]
  def index
    @user = User.new
  end
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/login/_form.html.erb
<% botton_text ||= 'Submit' %>
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="actions">
    <%= form.submit botton_text %>
  </div>
<% end %>

app/views/login/about.html.erb
author:
    </br>
      xindi.wang，s3279200

app/views/login/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/login/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Login</h1>

<%= form_for @user, url: login_users_path do |form| %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="actions">
    <%= form.submit "Log in" %>
  </div>
<% end %>

<h1>creat account</h1>

<%= render 'form', user: @user, botton_text: 'create' %>
<style>
  body {
    text-align: center;
  }
</style>

app/views/login/new.html.erb
<h1>Sign up</h1>

<%= render 'form', user: @user, botton_text: 'Sign up' %>

app/views/login/show.html.erb
<div class="alert alert-success" role="alert"><%= notice %></div>
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', news_index_path %>