config/routes.rb
Rails.application.routes.draw do
  root :to => 'news#index'
  resources :comments
  resources :newcomments
  resources :users do
    collection do
      get :logout
      get :about
    end
  end
  resources :news
  resources :submit
  resources :login
  namespace :v0 do
    resources :comment
    resources :new
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if content_for?(:title) %><title><%= yield(:title) %></title><% else %><%= content_tag :title, 'Hacker' %><% end %><%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <header class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="https://news.ycombinator.com/">
            <%= image_tag "hacker_icon.png", size: '30x30', style: 'display: inline;' %>
            RMIT News
          </a>
        </div>

        <div class="navbar-collapse"">
          <ul class="nav navbar-nav ">
            <li class="<%= current_page?(news_index_path) ? 'active' : '' %>"><%= link_to 'Home' , news_index_path %></li>
            <li class="<%= current_page?(newcomments_path) ? 'active' : '' %>"><%= link_to 'Comments' , newcomments_path %></li>
            <li class="<%= current_page?(submit_index_path) ? 'active' : '' %>"><%= link_to 'Submit' , submit_index_path %></li>
          </ul>
          <p class="navbar-text navbar-right">
            <% if signed_user %>
              <%= link_to signed_user.username, user_path(signed_user.id), class: 'navbar-link' %>
              ,
              <%= link_to 'Sign out', logout_users_path, class: 'navbar-link' %>
            <% else %>
              <%= link_to 'Sign in', login_index_path, class: 'navbar-link' %>
            <% end %>
          </p>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>

  <footer class="page-footer", style="height: 33px;">
      <div class="footer-copyright py-3 text-center">
          <a href="https://github.com/pigfly/RMIT-CSIT-RAD/tree/master/2018_S1/assignment2"> API </a> | <a href="users/about"> About </a>
      </div>
  </footer>
  </body>
</html>